version '3.8'
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
  frontend:
    build: ./web
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app
